name: MuXTalk_Streamlit
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - streamlit=1.11.0=py39hecd8cb5_0
  - networkx=2.6.2=pyhd3eb1b0_0
  - pyvis=0.1.9=pyhd8ed1ab_0
  - numpy=1.21.1=py39h7eed0ac_0
  - pandas=1.4.4=py39he9d5cce_0
  - tqdm=4.64.1=py39hecd8cb5_0
  - scipy=1.6.2=py39hd5f7400_1
  - altair=4.1.0=py_1
